.catalog:
  name: "WordPress"
  version: "v4.8"
  description: "WordPress with external MySQL container"
  uuid: registry-3
  questions:
    - variable: "WORDPRESS_DB_NAME"
      label: "WordPress MySQL Database"
      description: "WordPress MySQL Database"
      required: true

    - variable: "WORDPRESS_DB_USER"
      label: "WordPress MySQL User"
      description: "WordPress Mysql database user name"
      required: true

    - variable: "WORDPRESS_DB_PASSWORD"
      label: "WordPress MySQL Database Password"
      description: "WordPress MySQL Database password"
      required: true
      type: "password"

version: '2'
services:
  wordpress:
    scale: 1
    start_on_create: true
  wordpress-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: wordpress
        source_port: 8002
        target_port: 80
      stickiness_policy:
        cookie: rt-wordpress
        domain: .new.rnaktrail.se
        indirect: false
        mode: insert
        nocache: false
        postonly: false
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
